# Generated by Django 3.0.3 on 2020-02-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20200214_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rack',
            field=models.ManyToManyField(blank=True, related_name='students', to='rest.Rack'),
        ),
    ]
